$ErrorActionPreference = 'Stop'
$repo = 'Mattel-Limbo/psdfy'
$dir  = Join-Path $env:TEMP 'psdfy-issues'
if (Test-Path $dir) { Remove-Item -Recurse -Force $dir }
New-Item -ItemType Directory -Path $dir | Out-Null

$issues = @(
@{ t = '[P0] Project scaffolding and pyproject.toml';
   b = @"
Set up the repository skeleton so every later issue has a clear place to land.

**Scope**
- Create the folder structure described in ``plan.md`` section 11 (``app/``, ``web/``, ``psdfy/``, ``tests/``, ``scripts/``, ``weights/``, ``outputs/``, ``docker/``).
- Add ``pyproject.toml`` with project metadata, Python ``>=3.11``, and ``[project.scripts] psdfy = "psdfy.cli:app"``.
- Add ``.env.example`` matching plan.md section 19 (host, ``APP_API_PORT=3456``, ``APP_UI_PORT=3457``, auth, models).
- Add ``.gitignore`` (weights, outputs, .venv, .env, __pycache__).
- Add ``requirements.txt`` baseline from plan.md section 20.
- Add an empty ``README.md`` placeholder.
- Add Ruff + Black config; pre-commit optional.

**Done when**
- ``pip install -e .`` works in a clean venv.
- ``psdfy --help`` runs (even if commands are stubs).
- Lint passes on the empty tree.

Refs: plan.md section 11, 19, 20.
"@ },

@{ t = '[P0] Two FastAPI factories: api_app (3456) and ui_app (3457)';
   b = @"
Stand up two FastAPI applications so all later work can target the right surface.

**Scope**
- ``app/api_app/factory.py`` exposes ``build_api_app() -> FastAPI``.
- ``app/ui_app/factory.py`` exposes ``build_ui_app() -> FastAPI``.
- ``app/main.py`` re-exports ``api_app`` and ``ui_app``.
- Both apps register ``GET /health`` returning ``{ "status": "ok", "service": "<name>" }``.
- ``app/core/config.py`` (pydantic-settings) reads ``.env`` for ``APP_HOST``, ``APP_API_PORT`` (default ``3456``), ``APP_UI_PORT`` (default ``3457``).
- Run target: ``uvicorn app.main:api_app --host localhost --port 3456`` and ``uvicorn app.main:ui_app --host localhost --port 3457``.

**Done when**
- Both servers start independently and ``/health`` returns 200 on each.
- Default host is ``localhost``; setting ``APP_HOST=0.0.0.0`` exposes both.

Refs: plan.md section 4, 5, 11.
"@ },

@{ t = '[P1] Client Signature: POST /auth/client-signature + verifier middleware';
   b = @"
Implement the auth scheme defined in plan.md section 28.

**Scope**
- ``POST /auth/client-signature`` on ``api_app``. Body: ``{ clientSecret, clientUnixTimestamps }``. Validate ``clientSecret`` is UUIDv4, timestamp within ``SIGNATURE_TIMESTAMP_SKEW``.
- Generate ``sessionId`` (UUIDv4) and 10-char alphanumeric ``salt``.
- Compute signature: ``base64(HMAC_SHA256(key=clientSecret(+pepper), msg=ts+salt))``.
- Persist session record (sessionId, clientSecretHash, salt, signature, ts, expiresAt, revoked) in an in-memory store with a pluggable interface (``memory`` / ``sqlite`` / ``redis``).
- Middleware on protected routes validates ``X-Session-Id`` + ``X-Client-Signature`` using ``hmac.compare_digest``.
- Errors: 401 missing/invalid, 403 expired/revoked. Never reveal which check failed.
- Helpers ``build_signature``, ``verify_signature`` live in ``app/core/security.py``.

**Done when**
- Curl example in plan.md section 28.5 succeeds end to end against ``api_app``.
- Unauthenticated ``POST /convert`` returns 401.

Refs: plan.md section 28.
"@ },

@{ t = '[P1] Signature math unit tests + session store tests';
   b = @"
Lock down the auth primitives with deterministic tests.

**Scope**
- Unit tests for ``build_signature`` against fixed ``clientSecret``, ``ts``, ``salt`` vectors.
- Unit tests for issuance flow: bad UUID, skewed timestamp, valid input.
- Unit tests for verifier: missing headers, mismatched signature, expired session, revoked session.
- Tests for the in-memory session store contract (put/get/expire/revoke).
- Use ``httpx.AsyncClient`` against ``api_app`` for end-to-end flow tests.

**Done when**
- ``pytest tests/test_auth_signature.py`` is green.
- Coverage on ``app/core/security.py`` is greater than 90%.

Refs: plan.md section 24, 28.
"@ },

@{ t = '[P2] POST /convert: file validation + placeholder PSD';
   b = @"
Wire ``/convert`` end-to-end with a flat PSD before plugging in any models.

**Scope**
- ``POST /convert`` on ``api_app``, behind Client Signature middleware.
- Multipart fields: ``file`` (required), ``mode`` (auto|prompt), ``prompt``, ``return_previews``, ``return_metadata``.
- Validate MIME by magic bytes; enforce ``MAX_UPLOAD_MB``, ``MAX_IMAGE_DIM``, allowed types (jpg, jpeg, png, webp).
- For now, ignore segmentation. Return a single-layer PSD (the input image) generated by ``pytoshop``.
- Response shape per plan.md section 17.
- Error responses per plan.md section 23 with ``request_id``.

**Done when**
- Uploading a JPG returns a ``.psd`` openable in Photoshop with 1 layer named ``image``.
- All documented 4xx error codes are reachable.

Refs: plan.md section 4, 17, 23.
"@ },

@{ t = '[P2] SAM 2 loader and segmenter (auto-mask mode)';
   b = @"
Integrate Meta's SAM 2 as the primary segmenter.

**Scope**
- ``app/models/sam2_loader.py`` lazy-loads weights from ``SAM2_WEIGHTS_PATH`` once at startup.
- ``app/services/segmenter.py`` exposes ``segment_auto(image: np.ndarray) -> list[Mask]`` using SAM 2's automatic mask generator.
- Respect ``DEVICE`` (cuda/cpu/mps).
- Resize input to ``MAX_INFER_SIZE`` keeping aspect ratio; scale masks back to original.
- Return a typed ``Mask`` dataclass with ``mask`` (HxW bool), ``bbox``, ``area``, ``score``.

**Done when**
- A fixture image yields more than 0 masks on CPU and on GPU.
- Loader is invoked once (verified via test or log).

Refs: plan.md section 6, 7, 10.
"@ },

@{ t = '[P2] Mask post-processing pipeline';
   b = @"
Clean up raw SAM 2 masks before they become PSD layers.

**Scope**
- ``app/services/mask_postprocess.py``:
  - drop masks below ``MIN_MASK_AREA_RATIO`` and above 0.95 of image,
  - NMS by IoU 0.85,
  - morphological open/close,
  - hole filling,
  - 1-2 px alpha feathering.
- Pure-function design; takes/returns ``list[Mask]``.

**Done when**
- Unit tests cover area filter, NMS, morphology, hole filling on synthetic masks.
- Integration: pipeline never returns masks with area = 0 or NaNs.

Refs: plan.md section 13.
"@ },

@{ t = '[P2] Layer builder: per-mask RGBA + naive background';
   b = @"
Turn cleaned masks into RGBA layers and a background plate.

**Scope**
- ``app/services/layer_builder.py`` builds one RGBA layer per mask at the canvas size, transparent outside the mask.
- ``app/services/background_builder.py`` produces the simple background (image with foreground union set to transparent).
- Apply layer ordering rules from plan.md section 12.
- Crop each stored layer to its mask bbox; keep absolute offset for PSD position.

**Done when**
- Given N masks, builder returns N+1 layers (background + objects) in correct order.
- Layer sizes never exceed canvas; bboxes are valid.

Refs: plan.md section 12, 14.
"@ },

@{ t = '[P2] PSD writer with pytoshop (multi-layer output)';
   b = @"
Compose the final ``.psd`` from RGBA layers.

**Scope**
- ``app/services/psd_writer.py`` takes ordered RGBA layers + names + blend modes and writes a valid PSD via ``pytoshop``.
- Set ``name``, ``top/left/bottom/right``, ``blend_mode`` (default ``normal``).
- Bake a flattened composite into the merged image.
- Return bytes plus a path on disk.

**Done when**
- Generated PSD opens in Photoshop with all layers visible, named, and editable.
- A round-trip test reads the PSD back via ``psd-tools`` and asserts layer count + names + bbox.

Refs: plan.md section 16.
"@ },

@{ t = '[P2] Local storage backend + JSON response wiring';
   b = @"
Persist outputs and serve them from ``api_app``.

**Scope**
- ``app/storage/local_storage.py`` writes to ``STORAGE_LOCAL_DIR/{job_id}/...``.
- ``GET /files/{job_id}/{filename}`` serves PSD/preview/metadata behind signature middleware.
- ``POST /convert`` returns the JSON shape from plan.md section 17 with timing fields.
- Cleanup: on failure, remove partial files.

**Done when**
- Successful conversion writes ``output.psd`` and the response URL downloads it.
- Failed conversion leaves no partial files.

Refs: plan.md section 17, 22.
"@ },

@{ t = '[P3] UI app: login page + cookie session + bcrypt password';
   b = @"
Add the password gate for the GUI Web server.

**Scope**
- ``GET /login`` renders a Jinja2 form.
- ``POST /ui/login`` bcrypt-verifies password against ``ui_password_hash`` from ``~/.psdfy/config.toml`` (fallback to ``UI_PASSWORD`` env, default ``123456``).
- On success: server mints a ``clientSecret`` (from config), calls the same internal logic as ``POST /auth/client-signature``, stores ``sessionId`` + ``clientSignature`` server-side keyed by an ``itsdangerous``-signed cookie (``UI_COOKIE_NAME``).
- ``POST /ui/logout`` clears the cookie and revokes the session.
- Apply ``ui_session`` middleware to all protected UI routes.

**Done when**
- Visiting ``/`` while logged out redirects to ``/login``.
- Correct password returns 302 to ``/``; wrong password returns 401 with form re-render.

Refs: plan.md section 4, 19, 30.3.
"@ },

@{ t = '[P3] UI app: single-page shell with side menu';
   b = @"
Build the minimal SPA layout described in plan.md section 30.

**Scope**
- ``web/templates/base.html``, ``app.html``, ``login.html``.
- Tailwind via CDN, vanilla JS, no build step.
- Layout: header (logo + Logout), side menu (Convert active; Settings/About placeholders), main panel (drag-drop, browse, Convert button, progress, results).
- Mobile: side menu collapses into a hamburger.
- All copy goes through ``web/static/js/i18n.js``.

**Done when**
- Logged-in user sees the shell at ``/``.
- Side menu Convert is active; Settings/About are visible but disabled.
- Layout renders correctly on 360px and 1440px widths.

Refs: plan.md section 30.
"@ },

@{ t = '[P3] UI app: /ui/convert server-side proxy + /ui/job progress';
   b = @"
Let the browser upload without ever seeing the signature.

**Scope**
- ``POST /ui/convert`` reads the multipart upload, attaches ``X-Session-Id`` and ``X-Client-Signature`` from the cookie-bound session, and forwards to ``http://<host>:<api_port>/convert`` via ``app/utils/http_client.py``.
- Stream the response back; do not buffer large PSDs in memory.
- ``GET /ui/job/{job_id}`` exposes pipeline progress (poll or SSE) with stages: ``load``, ``segment``, ``compose``, ``done``.
- Frontend ``web/static/js/app.js`` posts the file, polls progress, renders preview thumbnails, exposes Download buttons.

**Done when**
- A file uploaded through the UI ends up in ``outputs/`` and the user can download the PSD.
- Browser DevTools never see ``clientSecret`` or ``clientSignature``.

Refs: plan.md section 4, 30.3, 30.4.
"@ },

@{ t = '[P4] psdfy CLI scaffold (Typer) + psdfy version';
   b = @"
Bootstrap the user-facing CLI.

**Scope**
- ``psdfy/cli.py`` builds a Typer app and registers subcommands ``install``, ``start``, ``stop``, ``update``, ``version``, ``fix`` (others may be stubs).
- ``psdfy version`` prints psdfy version, service version, python, torch+device, weight checksums, config path (format from plan.md section 29.6).
- ``psdfy/__main__.py`` enables ``python -m psdfy``.
- ``[project.scripts] psdfy = "psdfy.cli:app"`` in ``pyproject.toml``.

**Done when**
- ``psdfy --help`` lists all commands.
- ``psdfy version`` prints the expected block.

Refs: plan.md section 29.1, 29.6.
"@ },

@{ t = '[P4] psdfy install (config.toml, weights, password, optional service)';
   b = @"
Make first-run setup a single command.

**Scope**
- Detect OS + Python (>= 3.11).
- Create ``~/.psdfy/`` and subdirs (``weights/``, ``outputs/``, ``run/``).
- Prompt for password (default ``123456``), bcrypt-hash, store in ``config.toml``.
- Generate ``clientSecret`` (UUIDv4) and ``signature_pepper`` (32 random bytes hex).
- Download SAM 2 (and optionally GroundingDINO) weights with checksum verification, unless ``--no-weights``.
- Write ``~/.psdfy/config.toml`` with ``[app] host``, ``api_port=3456``, ``ui_port=3457``, ``device``, plus ``[auth]``, ``[models]``, ``[meta]``.
- ``--service`` registers NSSM (Windows), ``launchd`` (macOS), or ``systemd --user`` (Linux).
- Idempotent: re-running updates password/ports/host without redownloading weights.

**Done when**
- On a clean Windows 11 and macOS, ``pipx install psdfy && psdfy install --password test123`` succeeds end to end.
- ``psdfy install`` is rerunnable without errors.

Refs: plan.md section 29.2.
"@ },

@{ t = '[P4] psdfy start (PID files, port pre-flight, foreground mode)';
   b = @"
Bring both servers up with one command.

**Scope**
- Read ``~/.psdfy/config.toml``. Flags ``--host``, ``--api-port``, ``--ui-port`` override per invocation only.
- Pre-flight: both ports free, weights present.
- Spawn ``uvicorn app.main:api_app --port <api_port>`` and ``uvicorn app.main:ui_app --port <ui_port>``.
- Write PIDs to ``~/.psdfy/run/api.pid`` and ``~/.psdfy/run/ui.pid``; logs to ``api.log`` / ``ui.log``.
- Wait until ``/health`` returns 200 on both (timeout 30s).
- ``--foreground`` streams logs to stdout.
- If already running (PIDs alive), print status and exit 0.
- If ``--service`` was used at install time, delegate to the platform service manager.

**Done when**
- ``psdfy start`` brings both servers up; UI is reachable at ``http://localhost:3457``, API at ``http://localhost:3456``.
- Re-running while up does not double-spawn.

Refs: plan.md section 29.3.
"@ },

@{ t = '[P4] psdfy stop (graceful SIGTERM, --force, service-manager delegation)';
   b = @"
Shut both servers down cleanly.

**Scope**
- Read PIDs from ``~/.psdfy/run/``.
- Send SIGTERM (Windows: ``taskkill /PID``); wait up to 10s for clean exit.
- ``--force`` escalates to SIGKILL / ``taskkill /F``.
- Delete PID files; keep log files.
- If ``--service`` was used at install time, delegate to the platform service manager.
- Exit 0 if both stopped (or already stopped); 1 otherwise.

**Done when**
- ``psdfy stop`` after ``psdfy start`` leaves no listening sockets on 3456/3457.
- ``psdfy stop`` is safe when nothing is running.

Refs: plan.md section 29.4.
"@ },

@{ t = '[P4] psdfy fix (diagnose and repair)';
   b = @"
Give users a single command to recover a broken install.

**Scope**
- Checks: Python version, ``config.toml`` parses, weights present + sha256 ok, ports free, GPU detection matches ``device``, service status if installed.
- Flags: ``--reset-password`` (rewrites bcrypt hash; default back to ``123456`` if blank), ``--reset-client-secret`` (mints new UUIDv4), ``--redownload-weights``, ``--reset-config`` (with warning), ``--dry-run`` reports only.
- Report uses Rich tables; offers interactive fixes.
- Exit codes: 0 healthy/fixed, 1 issues remain, 2 user aborted.

**Done when**
- Deleting weights and running ``psdfy fix --redownload-weights`` restores a working install.
- ``psdfy fix --dry-run`` never modifies anything.

Refs: plan.md section 29.7.
"@ },

@{ t = '[P5] Preview PNGs + metadata.json output';
   b = @"
Add the optional artifacts described in the API contract.

**Scope**
- When ``return_previews=true``, write per-layer PNGs to ``outputs/{job_id}/preview_<name>.png`` and include URLs in the response.
- When ``return_metadata=true``, write ``metadata.json`` matching plan.md section 18 (job_id, source, model, layers with bbox/area/blend mode, generated_at).
- Add per-stage timings (``load``, ``segmentation``, ``postprocess``, ``psd_write``, ``total``) to the response.

**Done when**
- An end-to-end conversion produces previews and metadata that match the plan.md examples shape-for-shape.

Refs: plan.md section 17, 18.
"@ },

@{ t = '[P5] Structured logging + request_id correlation across both apps';
   b = @"
Make incidents debuggable without leaking secrets.

**Scope**
- Use ``structlog`` (or stdlib + JSON formatter) on both ``api_app`` and ``ui_app``.
- Inject ``request_id`` middleware (generate or accept ``X-Request-Id``).
- Propagate ``request_id`` from ``ui_app/proxy`` to ``api_app/convert`` via header.
- Redact ``clientSecret``, ``clientSignature``, password, cookie value in all logs.
- Log start/end of each pipeline stage with timing.

**Done when**
- Every request emits start + end JSON log lines with the same ``request_id``.
- Secrets never appear in logs (verified by a redaction unit test).

Refs: plan.md section 22, 23.
"@ },

@{ t = '[P5] Tests: unit + API + CLI + PSD round-trip';
   b = @"
Reach the test coverage promised in plan.md section 24.

**Scope**
- Unit: signature, mask postprocess, naming, geometry helpers.
- Service: conversion service with a mocked segmenter returning deterministic masks.
- API: ``httpx.AsyncClient`` against ``api_app`` and ``ui_app`` covering happy paths and every documented 4xx/5xx code.
- CLI: Typer's ``CliRunner`` for ``install --dry-run``, ``version``, ``start --dry-run``, ``stop --dry-run``, ``fix --dry-run``.
- PSD round-trip: write with ``pytoshop``, read with ``psd-tools``, assert layers/names/bbox/blend modes.

**Done when**
- ``pytest -q`` is green on CPU.
- Heavy model tests are gated behind ``MODELS=1``.

Refs: plan.md section 24.
"@ },

@{ t = '[P5] CI pipeline (lint, type-check, tests)';
   b = @"
Stop regressions before they ship.

**Scope**
- GitHub Actions workflow: setup Python 3.11 and 3.12 on ubuntu-latest and windows-latest.
- Steps: ``pip install -e .[dev]``, ``ruff check``, ``black --check``, ``mypy --strict app psdfy``, ``pytest -q``.
- Cache pip and pre-commit.
- Block merges on red CI.

**Done when**
- A PR with a failing test cannot be merged.
- Matrix is green on a clean main.

Refs: plan.md section 22, 24.
"@ },

@{ t = '[P6] GroundingDINO integration + mode=prompt';
   b = @"
Promote layers from ``object_N`` to real names.

**Scope**
- ``app/models/dino_loader.py`` lazy-loads GroundingDINO weights from ``DINO_WEIGHTS_PATH``.
- ``app/services/segmenter.py`` adds ``segment_with_prompt(image, prompt)``: DINO returns boxes -> SAM 2 returns masks per box.
- Default vocabulary from ``DEFAULT_PROMPT`` env var when ``mode=auto`` and ``ENABLE_GROUNDING_DINO=true``.
- Carry ``label`` and ``confidence`` through ``Mask`` dataclass into PSD layer names.

**Done when**
- ``mode=prompt`` with ``prompt='person . table . book . cup'`` returns named layers in the PSD.
- Layer names sanitized (length, control chars).

Refs: plan.md section 6, 7, 10, 12.
"@ },

@{ t = '[P6] Layer naming and dedup improvements';
   b = @"
Make layer ordering and names production-quality.

**Scope**
- Dedup masks at IoU > 0.85 keeping higher-confidence one.
- Layer order per plan.md section 12 (background, shadow, static scene by area desc, foreground by vertical position, main_object on top).
- Detect ``main_object`` as largest salient non-full mask.
- Sanitize layer names (length cap, ASCII fallback for PSD compatibility).
- Fall back to ``object_N`` when no DINO label exists.

**Done when**
- Multi-object fixture image yields predictable, ordered, named layers across runs.

Refs: plan.md section 12.
"@ },

@{ t = '[P7] Background inpainting (LaMa)';
   b = @"
Turn the background plate into a clean, complete layer.

**Scope**
- Add LaMa loader (or a lighter inpainting alternative) gated by ``ENABLE_BACKGROUND_INPAINT``.
- After computing the union of foreground masks, dilate slightly and inpaint the holes.
- Fall back to ``cv2.inpaint`` on failure.
- ``metadata.json`` records ``inpainted: true/false`` per background layer.

**Done when**
- For a sample image, the background layer alone (with all foregrounds hidden) shows no large transparent holes.

Refs: plan.md section 14.
"@ },

@{ t = '[P7] Shadow layer extraction (multiply blend)';
   b = @"
Generate a best-effort shadow layer.

**Scope**
- ``app/services/shadow_builder.py`` uses LAB color heuristic from plan.md section 15.
- Output stored as a layer with ``blend_mode=multiply``, name ``shadow``.
- Toggle via ``ENABLE_SHADOW_LAYER`` and per-request ``detect_shadow=false``.
- Document as best-effort in README.

**Done when**
- Image with a clear ground shadow yields a usable ``shadow`` layer that composites correctly when toggled on/off in Photoshop.

Refs: plan.md section 15.
"@ },

@{ t = '[P7] Alpha matting (pymatting) for tricky edges';
   b = @"
Improve hair, fur, and glass cutouts.

**Scope**
- Optional refinement step using ``pymatting`` with a trimap derived from each mask.
- Gated by env flag ``ENABLE_ALPHA_MATTING``.
- Apply only to masks where edge gradient stats suggest soft boundaries.

**Done when**
- A portrait fixture has visibly cleaner hair edges with the flag enabled vs disabled.

Refs: plan.md section 13.
"@ },

@{ t = '[P7] Async job queue (Arq + Redis) + polling';
   b = @"
Decouple slow inference from request handlers.

**Scope**
- Add Arq worker entrypoint; ``POST /convert`` enqueues a job and returns ``job_id`` with ``status=queued``.
- ``GET /convert/{job_id}`` returns status + final response when done.
- ``ui_app`` proxies/polls the same job interface.
- Configurable: in-process for MVP, Redis-backed for production.

**Done when**
- Concurrent uploads do not block each other; UI shows progress for queued vs running.

Refs: plan.md section 9.
"@ },

@{ t = '[P7] S3 storage backend + API keys + rate limiting';
   b = @"
Make the deployment cloud-friendly.

**Scope**
- ``app/storage/s3_storage.py`` implements the same interface as local storage; switched via ``STORAGE_BACKEND=s3``.
- Sign download URLs with short TTL.
- Optional API key auth as an alternative to Client Signature for trusted clients (header ``X-API-Key``).
- Rate-limit ``POST /auth/client-signature`` (per IP) and ``POST /convert`` (per session).

**Done when**
- A deployment with S3 returns signed URLs that download successfully and expire on time.
- Hitting the rate limit returns 429 with a ``Retry-After``.

Refs: plan.md section 6, 9, 22, 28.6.
"@ },

@{ t = '[P8] psdfy update (PyPI release flow + config migration)';
   b = @"
Let users upgrade in place.

**Scope**
- Query PyPI for latest ``psdfy`` on ``--channel stable|beta``.
- Compare with ``installed_version`` in ``config.toml``.
- Run ``pipx upgrade psdfy`` (or pip in managed venv).
- Run registered config migrations (versioned).
- Restart service if installed with ``--service``; otherwise restart via ``psdfy stop && psdfy start``.
- Print release notes URL.

**Done when**
- Bumping the version on PyPI and running ``psdfy update`` upgrades the install and restarts servers without manual steps.

Refs: plan.md section 29.5, 31.3.
"@ },

@{ t = '[P8] Dockerfile + GPU image + benchmarks';
   b = @"
Ship a reproducible container and a perf reference.

**Scope**
- ``docker/Dockerfile`` (CPU) and ``docker/Dockerfile.gpu`` (CUDA base).
- Multi-stage build; non-root user; healthcheck hits ``:3456/health``.
- Bake or mount weights via volume.
- ``scripts/benchmark.py`` reports per-stage timings on a fixed image set; outputs JSON for CI tracking.
- Document target latency: less than 5s on GPU at 1080p.

**Done when**
- ``docker run`` with mounted weights serves the API on 3456 and UI on 3457.
- ``python scripts/benchmark.py`` produces a stable JSON report.

Refs: plan.md section 6, 26, 31.
"@ }
)

$i = 1
foreach ($it in $issues) {
  $f = Join-Path $dir ("issue_{0:00}.md" -f $i)
  Set-Content -Path $f -Value $it.b -Encoding UTF8
  $url = gh issue create --repo $repo --title $it.t --body-file $f 2>&1 | Select-Object -Last 1
  Write-Host ("[{0:00}] {1} -> {2}" -f $i, $it.t, $url)
  $i++
}

Write-Host ""
Write-Host ("Done. {0} issues attempted in {1}" -f $issues.Count, $repo)
